### ISSUE TITLE
Experiment with the value of Indexer::LIMIT

### ISSUE THREAD

**Issue by evis-e** [codeGUST-SE/indexer#18]

**Comment by mustiikhalil** [comment]
Indexing 1049 entries.
Takes with 100 limit: 
Takes with 50 limit:
Takes with 150 limit:
Takes with 10 limit:

**Comment by evis-e** [comment]
So after the experiment, are we making the limit 250?

**Comment by mustiikhalil** [comment]
Yes, according to the benchmark table.
